### ISSUE TITLE
What's the usage for this?

### ISSUE THREAD

**Issue by christianbundy** [l4u/gifsicle-heroku#1]
I'm trying to get gifscile running on Heroku, how do I use this repository? Thanks!

**Comment by l4u** [comment]
You can use the binary inside gifsicle-1.7.0.tgz on Heroku Cedar.
Alternatively you can build the binary yourself with the script in README.

**Comment by christianbundy** [comment]
Is there a buildpack to accompany this? I'm trying to get it running as a dependency on Cedar and I can't figure it out.

**Comment by l4u** [comment]
There's no build pack for it.
A easier method is to include the compiled binary in your source repo.
